// definition of PLC operation command
U_PLC_POS_REGS  = 0;        // PLC Register No.
U_PLC_POS_SIZE  = 1;        // Data Length
U_PLC_POS_DAT1  = 2;        // Data 1
U_PLC_POS_DAT2  = 3;        // Data 2
U_PLC_POS_DAT3  = 4;        // Data 3
U_PLC_POS_DAT4  = 5;        // Data 4
U_PLC_POS_DAT5  = 6;        // Data 5
U_PLC_POS_DAT6  = 7;        // Data 6
U_PLC_POS_DAT7  = 8;        // Data 7
U_PLC_POS_DAT8  = 9;        // Data 8
U_PLC_POS_DAT9  = 10;       // Data 9

// definition of PLC tracking area
U_ECS_WRT_SERL = 0;         // PC Write 영역 (작업번호)
U_ECS_WRT_DEST = 1;         // PC Write 영역 (목적지)
U_ECS_WRT_WINT = 2;         // PLC Write 영역 무게 정수
U_ECS_WRT_WFLT = 3;         // PLC Write 영역 무게 소수점
U_PLC_WRT_MODE = 4;         // PLC Write 영역
U_PLC_WRT_EROR = 5;         // PLC Write 영역
U_PLC_WRT_STAT = 6;         // PLC Write 영역
U_PLC_WRT_SENS = 7;         // PLC Write 영역
U_PLC_WRT_MOTR = 8;         // PLC Write 영역

// definition of PLC No
U_PLT_PLC = 1;
U_BOX_PLC = 2;

// definition of CNV MODE
U_CNV_IN_MODE = 0;
U_CNV_OUT_MODE = 1;


